builds:
  - id: "multiproxy"
    main: "./cmd/multiproxy"
    binary: "./multiproxy"
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-s -w"
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: "multiproxy"
    format: zip
    builds:
      - "multiproxy"
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: linux
        format: tar.gz

release:
  prerelease: auto
  name_template: "{{.ProjectName}}-{{.Version}}"
  extra_files:
    - glob: "./dist/other/*"

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
